### ISSUE TITLE
package version

### ISSUE THREAD

**Issue by TyuutoHannpa** [IDEALLab/bezier-gan#7]
Please let me know which version of the package you need.

**Comment by TyuutoHannpa** [comment]
I would like to know the operating environment version.

**Comment by wchen459** [comment]
There is no requirement on the operating environment version, though the code was tested on Ubuntu. Tensorflow version needs to be below 2.0. I tested the code on tf 1.14.0 if I remembered correctly. I did not keep track of versions of other packages but any version should work if they are compatible with each other.

**Comment by TyuutoHannpa** [comment]
thank you
